kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-scheduler
rules:
- apiGroups: [""]
  resources: ["pods", "pods/binding", "nodes", "events"]
  verbs: ["get", "list", "watch", "create", "update"]
